CREATE TABLE "Patients" (
  "PatientID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Sex" bool,
  "Age" int,
  "Education" int,
  "Income" int
);

CREATE TABLE "Health_Conditions" (
  "ConditionID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PatientID" int,
  "Diabetes_012" bool,
  "HighBP" bool,
  "HighChol" bool,
  "Stroke" bool,
  "HeartDiseaseorAttack" bool,
  "DiffWalk" bool
);

CREATE TABLE "Lifestyle_Factors" (
  "LifestyleID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PatientID" int,
  "BMI" float,
  "Smoker" bool,
  "PhysActivity" bool,
  "Fruits" bool,
  "Veggies" bool,
  "HvyAlcoholConsump" bool
);

CREATE TABLE "Health_Metrics" (
  "MetricsID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PatientID" int,
  "CholCheck" bool,
  "GenHlth" int,
  "MentHlth" int,
  "PhysHlth" int
);

CREATE TABLE "Healthcare_Access" (
  "AccessID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PatientID" int,
  "AnyHealthcare" bool,
  "NoDocbcCost" bool
);

COMMENT ON COLUMN "Patients"."Sex" IS '0 for female, 1 for male';

COMMENT ON COLUMN "Health_Conditions"."Diabetes_012" IS '0=no, 1=prediabetes, 2=diabetes';

COMMENT ON COLUMN "Health_Metrics"."CholCheck" IS 'Cholesterol check in last 5 years';

COMMENT ON COLUMN "Health_Metrics"."GenHlth" IS 'Scale 1-5';

COMMENT ON COLUMN "Health_Metrics"."MentHlth" IS 'Days of poor mental health in last 30 days';

COMMENT ON COLUMN "Health_Metrics"."PhysHlth" IS 'Days of poor physical health in last 30 days';

COMMENT ON COLUMN "Healthcare_Access"."NoDocbcCost" IS 'Could not see doctor due to cost';

ALTER TABLE "Health_Conditions" ADD FOREIGN KEY ("PatientID") REFERENCES "Patients" ("PatientID");

ALTER TABLE "Lifestyle_Factors" ADD FOREIGN KEY ("PatientID") REFERENCES "Patients" ("PatientID");

ALTER TABLE "Health_Metrics" ADD FOREIGN KEY ("PatientID") REFERENCES "Patients" ("PatientID");

ALTER TABLE "Healthcare_Access" ADD FOREIGN KEY ("PatientID") REFERENCES "Patients" ("PatientID");
