CREATE TABLE IF NOT EXISTS "ValidationLog" (
    "ValidationID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TableName" VARCHAR(50) NOT NULL,
    "PatientID" INT,
    "ColumnName" VARCHAR(50) NOT NULL,
    "Value" TEXT,
    "ValidationRule" VARCHAR(200) NOT NULL,
    "ErrorMessage" TEXT NOT NULL,
    "ValidatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ValidatedBy" VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_validationlog_patientid ON "ValidationLog"("PatientID");
CREATE INDEX IF NOT EXISTS idx_validationlog_validatedat ON "ValidationLog"("ValidatedAt");

CREATE OR REPLACE FUNCTION GetPatientProfile(patient_id_param INT)
RETURNS TABLE (
    "PatientID" INT,
    "Sex" BOOLEAN,
    "Age" INT,
    "Education" INT,
    "Income" INT,
    "ConditionID" INT,
    "Diabetes_012" INT,
    "HighBP" BOOLEAN,
    "HighChol" BOOLEAN,
    "Stroke" BOOLEAN,
    "HeartDiseaseorAttack" BOOLEAN,
    "DiffWalk" BOOLEAN,
    "LifestyleID" INT,
    "BMI" REAL,
    "Smoker" BOOLEAN,
    "PhysActivity" BOOLEAN,
    "Fruits" BOOLEAN,
    "Veggies" BOOLEAN,
    "HvyAlcoholConsump" BOOLEAN,
    "MetricsID" INT,
    "CholCheck" BOOLEAN,
    "GenHlth" INT,
    "MentHlth" INT,
    "PhysHlth" INT,
    "AccessID" INT,
    "AnyHealthcare" BOOLEAN,
    "NoDocbcCost" BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p."PatientID",
        p."Sex",
        p."Age",
        p."Education",
        p."Income",
        hc."ConditionID",
        hc."Diabetes_012",
        hc."HighBP",
        hc."HighChol",
        hc."Stroke",
        hc."HeartDiseaseorAttack",
        hc."DiffWalk",
        lf."LifestyleID",
        lf."BMI",
        lf."Smoker",
        lf."PhysActivity",
        lf."Fruits",
        lf."Veggies",
        lf."HvyAlcoholConsump",
        hm."MetricsID",
        hm."CholCheck",
        hm."GenHlth",
        hm."MentHlth",
        hm."PhysHlth",
        ha."AccessID",
        ha."AnyHealthcare",
        ha."NoDocbcCost"
    FROM "Patients" p
    LEFT JOIN "Health_Conditions" hc ON p."PatientID" = hc."PatientID"
    LEFT JOIN "Lifestyle_Factors" lf ON p."PatientID" = lf."PatientID"
    LEFT JOIN "Health_Metrics" hm ON p."PatientID" = hm."PatientID"
    LEFT JOIN "Healthcare_Access" ha ON p."PatientID" = ha."PatientID"
    WHERE p."PatientID" = patient_id_param;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION GetCompletePatientRecords(
    skip_count INT DEFAULT 0,
    limit_count INT DEFAULT 1000
)
RETURNS TABLE (
    "PatientID" INT,
    "Sex" BOOLEAN,
    "Age" INT,
    "Education" INT,
    "Income" INT,
    "Diabetes_012" INT,
    "HighBP" BOOLEAN,
    "HighChol" BOOLEAN,
    "Stroke" BOOLEAN,
    "HeartDiseaseorAttack" BOOLEAN,
    "DiffWalk" BOOLEAN,
    "BMI" REAL,
    "Smoker" BOOLEAN,
    "PhysActivity" BOOLEAN,
    "Fruits" BOOLEAN,
    "Veggies" BOOLEAN,
    "HvyAlcoholConsump" BOOLEAN,
    "CholCheck" BOOLEAN,
    "GenHlth" INT,
    "MentHlth" INT,
    "PhysHlth" INT,
    "AnyHealthcare" BOOLEAN,
    "NoDocbcCost" BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p."PatientID",
        p."Sex",
        p."Age",
        p."Education",
        p."Income",
        hc."Diabetes_012",
        hc."HighBP",
        hc."HighChol",
        hc."Stroke",
        hc."HeartDiseaseorAttack",
        hc."DiffWalk",
        lf."BMI",
        lf."Smoker",
        lf."PhysActivity",
        lf."Fruits",
        lf."Veggies",
        lf."HvyAlcoholConsump",
        hm."CholCheck",
        hm."GenHlth",
        hm."MentHlth",
        hm."PhysHlth",
        ha."AnyHealthcare",
        ha."NoDocbcCost"
    FROM "Patients" p
    INNER JOIN "Health_Conditions" hc ON p."PatientID" = hc."PatientID"
    INNER JOIN "Lifestyle_Factors" lf ON p."PatientID" = lf."PatientID"
    INNER JOIN "Health_Metrics" hm ON p."PatientID" = hm."PatientID"
    INNER JOIN "Healthcare_Access" ha ON p."PatientID" = ha."PatientID"
    ORDER BY p."PatientID" DESC
    OFFSET skip_count
    LIMIT limit_count;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_bmi()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW."BMI" IS NOT NULL AND (NEW."BMI" < 10.0 OR NEW."BMI" > 100.0) THEN
        INSERT INTO "ValidationLog" (
            "TableName",
            "PatientID",
            "ColumnName",
            "Value",
            "ValidationRule",
            "ErrorMessage",
            "ValidatedBy"
        ) VALUES (
            'Lifestyle_Factors',
            NEW."PatientID",
            'BMI',
            NEW."BMI"::TEXT,
            'BMI must be between 10.0 and 100.0',
            'Invalid BMI value: ' || NEW."BMI"::TEXT,
            current_user
        );
        
        RAISE EXCEPTION 'BMI must be between 10.0 and 100.0. Provided: %', NEW."BMI";
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION audit_diabetes_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF OLD."Diabetes_012" IS DISTINCT FROM NEW."Diabetes_012" THEN
            RAISE NOTICE 'Diabetes_012 changed for PatientID %: % -> % by %', 
                NEW."PatientID", 
                COALESCE(OLD."Diabetes_012"::TEXT, 'NULL'), 
                COALESCE(NEW."Diabetes_012"::TEXT, 'NULL'),
                current_user;
        END IF;
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        RAISE NOTICE 'Diabetes_012 inserted for PatientID %: % by %', 
            NEW."PatientID", 
            COALESCE(NEW."Diabetes_012"::TEXT, 'NULL'),
            current_user;
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_validate_bmi ON "Lifestyle_Factors";
DROP TRIGGER IF EXISTS trigger_audit_diabetes ON "Health_Conditions";

CREATE TRIGGER trigger_validate_bmi
    BEFORE INSERT OR UPDATE OF "BMI" ON "Lifestyle_Factors"
    FOR EACH ROW
    EXECUTE FUNCTION validate_bmi();

CREATE TRIGGER trigger_audit_diabetes
    AFTER INSERT OR UPDATE OF "Diabetes_012" ON "Health_Conditions"
    FOR EACH ROW
    EXECUTE FUNCTION audit_diabetes_changes();
